### ISSUE TITLE
Reauthentication isn't working

### ISSUE THREAD

**Issue by ejholmes** [ejholmes/metaforce#44]
Getting INVALID_SESSION_ID:

```
A Savon::SOAP::Fault occurred in partners#edit:

  (sf:INVALID_SESSION_ID) INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00D30000000os...
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/soap/response.rb:107:in `raise_errors'
```

**Stack Trace**

```
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/soap/response.rb:107:in `raise_errors'
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/soap/response.rb:18:in `initialize'
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/soap/request.rb:35:in `new'
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/soap/request.rb:35:in `response'
  vendor/bundle/ruby/1.9.1/gems/savon-1.2.0/lib/savon/client.rb:86:in `request'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/abstract_client.rb:50:in `_request'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/abstract_client.rb:45:in `rescue in request'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/abstract_client.rb:39:in `request'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/services/client.rb:40:in `describe_layout'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/services/client.rb:59:in `picklist_values'
  vendor/bundle/ruby/1.9.1/gems/metaforce-1.0.6/lib/metaforce/client.rb:25:in `method_missing'
```

**Comment by se6wagner** [comment]
hi mate,

running into the same problem. It seems that in Metaforce::AbstractClient line 30

``` ruby
        client.config.soap_header = soap_headers
```

does not apply the new soap_header to the Savon client. I've written a custom authentication_handler that refreshes the OAuth token and overwrites options[:session_id] with the new token - running client.inspect at the end reveals that the the value is stored in the client's options. But the log shows that the second execution of 'request' still uses the old session id
