### ISSUE TITLE
Error passing Metadata type for list_metadata

### ISSUE THREAD

**Issue by AL9000** [ejholmes/metaforce#47]
When passing Metadata type that doesn't exist in an org, list_metadata returns a NoMethodError.

Example :

``` ruby
client.list_metadata('CampaignOwnerSharingRule')
```

returns :

```
c:/Ruby193/lib/ruby/gems/1.9.1/gems/metaforce-1.0.6/lib/metaforce/abstract_client.rb:51:in `_request': undefined method `result' for nil:NilClass (NoMethodError)
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/metaforce-1.0.6/lib/metaforce/abstract_client.rb:41:in `request'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/metaforce-1.0.6/lib/metaforce/metadata/client/file.rb:19:in `list_metadata'
```

**Comment by ejholmes** [comment]
Is `CampaignOwnerSharingRule` a newer metadata type? Can you try setting the api version to 27.0?

``` ruby
Metaforce.configure do |config|
  config.api_version = '27.0'
end
```

**Comment by AL9000** [comment]
I've set the api version to 27.0 and have the same result.
I've also done some tests and `ruby client.list_metadata(<meta>)` works only when `<meta>` exist in my org.

**Comment by loganm** [comment]
I've just encountered this issue myself. If there are no elements returned for a type of list_metadata call, then metaforce throws an exception.

I would have expected an empty results hash instead.

I worked around this by catching and ignoring the exception

``` ruby
begin
  client.list_metadata(t.xml_name).collect do |o|
    metadata << o.full_name
  end
  rescue Exception
end
```
